### ISSUE TITLE
"file" argument must be a non-empty string

### ISSUE THREAD

**Issue by ISNIT0** [skepticfx/fuzzcat#4]
When importing fuzzcat (`require('fuzzcat')`) the following error occurs:
Code:
```javascript
const fuzzcat = require('fuzzcat');
```

![image](https://user-images.githubusercontent.com/5173131/32940964-173b7a52-cb7c-11e7-97dc-7b7f994ef498.png)
```
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at spawnSync (child_process.js:510:38)
    at execSync (child_process.js:626:13)
    at sh (/Users/user/Projects/kafkaTools/node_modules/node-radamsa/index.js:5:10)
    at Object.<anonymous> (/Users/user/Projects/kafkaTools/node_modules/node-radamsa/index.js:9:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Node Version:
![image](https://user-images.githubusercontent.com/5173131/32940991-3262201a-cb7c-11e7-80ec-6a4bb7fe2836.png)

Radamsa Version:
![image](https://user-images.githubusercontent.com/5173131/32941009-4753e256-cb7c-11e7-9f46-7129fcc811e0.png)

Fuzzcat Version:
![image](https://user-images.githubusercontent.com/5173131/32941032-5de79350-cb7c-11e7-828f-72393542ddce.png)

**Comment by ISNIT0** [comment]
This is actually a node-radamsa issue:  https://github.com/skepticfx/node-radamsa/issues/2
